### ISSUE TITLE
project dev plan

### ISSUE THREAD

**Issue by ikorol3107** [Atlantis-Academy/react-learn-ikorol#1]
Составление плана разработки проекта ( c @themetronome ).

**Comment by themetronome** [comment]
Примерный план по разработке учебного проекта:

- Изучение [макета проекта](https://www.figma.com/file/wk4JVRtebicC874XqO1DAX/Watcher-2) и визуальное разделение приложения на независимые компоненты
- Конфигурация окружения проекта для разработки(временно - CRA), выбор инструментов и технологий для реализации
- Создание статического приложения. Вёрстка компонентов исходя из пункта 1 и 2, передача комопонентам данных через пропсы
- Реализация состояния компонентов, если это необходимо. Выбор того где хранить состояние, опять же из пункта 2
- Написание тестов
- Рефакторинг существующего кода
- Добавление новых фич в приложение

Если где-то ошибся надеюсь @TorinAsakura поправит меня
