### ISSUE TITLE
[task] Practice JS basics (part 1-3)

### ISSUE THREAD

**Issue by ikorol3107** [Atlantis-Academy/react-learn-ikorol#5]
Выполнить  задания по курсу JS basics: 
1) Практика, ч.1. Начинаем создавать приложение
2) Практика, ч2. Применяем условия и циклы*

*для выполнения ч.2 просмотреть видео уроки по темам Условия и Циклы.

**Comment by TorinAsakura** [comment]
Там будет код, который нужно выложить на гитхаб, части разбей на отдельные задачи и коммить код в соответствии в задачами
